// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psjjznbgktdkhikpodcq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzamp6bmJna3Rka2hpa3BvZGNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MTAwODksImV4cCI6MjA1OTQ4NjA4OX0.OOUg3e4TQj_ODPliGRmgwv0NzXUOWeCtsgtvSj6NHTw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);